### ISSUE TITLE
Tracks sometimes stutter a bit on first playback

### ISSUE THREAD

**Issue by aykevl** [devgianlu/go-librespot#115]
This issue is easiest to hear with the following track:
https://open.spotify.com/album/2dVSmVK9W05Mnmqgmg3SMX (track: "The Sun in Your Heart")
Pressing the same track in the album again triggers the issue again.

When you start playing the song, you can hear a short stutter at the beginning.
I assume it happens on many other tracks, but since most start with silence or ramp up volume it's less audible.

I tested on both my main system (Asahi Linux, over USB audio) and on a Raspberry Pi 3 (analog jack). I also tried with the PulseAudio patches in #86 but the same issue is present there (so it doesn't seem like a problem with the ALSA driver).

**Comment by aykevl** [comment]
Probably unrelated, but when debugging this issue I've seen messages like the following:

```
WARN[0121] failed handling dealer request                error="failed loading current track (load context): failed creating stream for spotify:track:1AGZTrBoRotCtDKYGZ70UA: failed retrieving audio key: failed retrieving aes key with code 2"
```

I suspect I got rate limited for a bit. It might be worth implementing some sort of cache :)

**Comment by aykevl** [comment]
I did some experimenting with a Go native Ogg Vorbis decoder (see https://github.com/aykevl/go-librespot/tree/vorbis-purego) and to my surprise the issue is not present there. This suggests that the bug is somewhere in the Vorbis decoder.

**Comment by devgianlu** [comment]
Seems strange to have a bug in the Vorbis decoder, perhaps it is a bug in how it is used? I see the native Go decoder also removes a bunch of code, but not sure if it would be appropriate to switch.

**Comment by aykevl** [comment]
> Seems strange to have a bug in the Vorbis decoder, perhaps it is a bug in how it is used?

Yeah that's what I mean, sorry. Maybe the first part gets accidentally decoded and played twice? Or it seeks to the start after starting to play or something?
Interestingly changing the ALSA buffer size has no effect.

> I see the native Go decoder also removes a bunch of code, but not sure if it would be appropriate to switch.

It mainly removes seek indices. The new code does support seek, but feels somewhat slow. (This could also be due to general sluggishness of Spotify Connect, need to test more carefully). That's one reason I haven't made a PR yet. The fact that it also seems to fix the stuttering is just luck.

**Comment by devgianlu** [comment]
> Yeah that's what I mean, sorry. Maybe the first part gets accidentally decoded and played twice? Or it seeks to the start after starting to play or something?

It may be putting frames in the internal buffer between the start of decoding and the initial seek. Just guessing, haven't reviewed the code.

> It mainly removes seek indices. The new code does support seek, but feels somewhat slow.

Yeah I see you removed the seek table stuff (`GetSeekPosition`, etc...). That I have reversed from the official Spotify client, including all the strange calculations and magic numbers.

**Comment by aykevl** [comment]
> Yeah I see you removed the seek table stuff (`GetSeekPosition`, etc...). That I have reversed from the official Spotify client, including all the strange calculations and magic numbers.

That certainly sounds like something we'd want to keep!
