### ISSUE TITLE
armv6_rpi binary not running on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by dr-erych** [devgianlu/go-librespot#145]
First of all: Thank you very much for this awesome port of librespot, and especially for not abandoning older Raspberry Pis.

After downloading and installing the prebuilt binary version for armv6 rpi [go-librespot_linux_armv6_rpi.tar.gz](https://github.com/devgianlu/go-librespot/releases/download/v0.1.2/go-librespot_linux_armv6_rpi.tar.gz), I don't succeed in running it. ("Illegal instruction")

I am using a RPI zero w with Raspberry Pi OS Lite (32-bit) Bookworm (12.8) 

When cloning the repo and building locally on the Raspberry Pi via `go build ./cmd/daemon`, it is working fine.

Can anyone confirm that it's not just me doing something wrong?

**Comment by devgianlu** [comment]
This is strange because the binary was made exactly for the Raspberry Pi Zero W. If it's not working I must have messed up the builds. Can you try an older build like v0.0.17?

**Comment by dr-erych** [comment]
Yep, I just tried with v0.0.17.1 and it is running.

**Comment by devgianlu** [comment]
Fixed with the builds from the latest commit: https://github.com/devgianlu/go-librespot/actions/runs/11869813895

Thanks for reporting! Next release will include working binaries.
