### ISSUE TITLE
After connecting Spotify App, the volume is always displayed as 100%

### ISSUE THREAD

**Issue by dr-erych** [devgianlu/go-librespot#146]
In my `config.yml`, I have `initial_volume` set to `20`.  
`volume_steps`, `mixer_device` and `mixer_control_name` are untouched.

After connecting a Spotify app (iOS or macOS), the volume control in the app is always displayed at full volume (100%), even though the actual volume on the go-librespot device is 20.

When later changing the volume in one of the apps, it is being propagated correctly to all other connected apps.

**Comment by szygmunt** [comment]
It's not only on apple's products, this bug is general. Maybe related to #147?

**Comment by devgianlu** [comment]
Should be fixed, thank you for reporting!
