### ISSUE TITLE
NFR: Playlists API

### ISSUE THREAD

**Issue by stronk-dev** [devgianlu/go-librespot#152]
For my `go-librespot`-based squeezebox I am only missing a few features:
- ([in progress](https://github.com/devgianlu/go-librespot/pull/124)) smart shuffle.
- (not important, nice for later) display the next song / retrieval of the play queue.
- being able to `play` from a stopped state or switch playlists

To enable the 3rd feature, ideally the `go-librespot` API has an endpoint to retrieve Spotify URI's of the playlists belonging to the connected account, maybe even the last played URI so that we can 'resume' where it last left off.

I am unfamiliar with Spotify's API and `librespot`'s codebase, but if these tasks seem doable with some pointers I would be up to working on a PR to add this.

**Comment by stronk-dev** [comment]
Yeah that works great... 🕳🐰

I think then the issue is probably more about enhancing the API docs - make a clear distinction between the features of the WebSocket, the REST API and the API passthrough for newcomers. I can submit a PR for this at some point

**Comment by devgianlu** [comment]
> I can submit a PR for this at some point

@stronk-dev That would be great! Closing this for now.
