### ISSUE TITLE
No option to configure Zeroconf port

### ISSUE THREAD

**Issue by odiroot** [devgianlu/go-librespot#154]
There is no configuration option to choose a specific Zeroconf port.
Both librespot-java and spotifyd/librespot had this option before. 

Currently go-librespot is selecting a random port. It works great with Spotify Connect indeed until you run it behind a firewall.
With a firewall running (e.g. firewalld) you would have to go and update the rules for the current random port selected by go-librespot. Otherwise your instance of go-librespot is not discoverable from other Spotify-running devices. 

Caveat: this still works if you use credentials storage. Because in that case go-librespot establishes its own connection to Spotify servers and "presents itself" to other devices as a sink. Still, without credential storage the service is not discoverable.

**Comment by devgianlu** [comment]
You're right, this was missing. I've implemented it, let me know if it works for you!

**Comment by odiroot** [comment]
> You're right, this was missing. I've implemented it, let me know if it works for you!

Thank you. Yes it does. That was quick :)
