### ISSUE TITLE
Control initial volume level

### ISSUE THREAD

**Issue by txoof** [devgianlu/go-librespot#21]
I've checked the config_schema.json(https://github.com/devgianlu/go-librespot/blob/master/config_schema.json), but I don't see an obvious way to set the initial volume level.

Is there a way to set it to a percentage or step N of Steps?

**Comment by devgianlu** [comment]
This should be implemented with https://github.com/devgianlu/go-librespot/commit/45fcffb1a96bc3bb2d5ba148d74a5bc9f03d8e7a, let me know how it goes for you.
