### ISSUE TITLE
Retrieve token through API

### ISSUE THREAD

**Issue by txoof** [devgianlu/go-librespot#22]
Is it possible to retrieve the token through the API?

In librespot-java it is possible to [fetch a token](https://github.com/librespot-org/librespot-java/blob/dev/api/README.md#tokens) that can be used for interacting with the spotify API. 

I don't see that in the documentation, but I may be misreading it or looking in the wrong place.

**Comment by devgianlu** [comment]
`librespot-java` uses the Mercury endpoint `/keymaster/token/authenticated` to generate token, but that does not seem to exist on spclient. `go-librespot` does not implement Mercury because it is an outdated Spotify API that I did not implement purposely. 

Not sure if there's another way to achieve this same result through another way, but that needs investigation.

**Comment by txoof** [comment]
@devgianlu Thanks for explaining. If there's a way to do this, I would find it super helpful.

**Comment by txoof** [comment]
Specifically, I'm interested in getting the higher resolution album art. Right now it looks like just the low resolution images are returned through the current go-librespot API.

I have an e-paper project that displays the now-playing artwork and I'd like the higher resolution images if I can get to them.

**Comment by devgianlu** [comment]
For the moment you might be able to retrieve those images from the official API: https://developer.spotify.com/documentation/web-api/reference/get-an-album

**Comment by txoof** [comment]
That was my original plan and it works well. 

The beauty of librespot zero config is ... zero configuration and no requirement for end users to need additional setup. I love this feature so much! Even the lower-resolution images are "good enough" for most use cases in terms of this project.

**Comment by 3052** [comment]
you can get it using the method from the Android client. beware, here be dragons:

https://github.com/3052/media/blob/main/blog/spotify/android/LoginOk.go

**Comment by felixstorm** [comment]
@devgianlu Is there any reason why we should not use the token we get from login5 and that go-librespot uses to authorize to the web api also for passthrough-requests received by the go-librespot API?

I implemented an API endpoint for it and during a few short tests it seems to work without any issues so far: https://github.com/felixstorm/go-librespot/commit/24707f74e56f872379e910b031feb8161e4ef71c  
If you would like me to I will be happy to open a PR for it.

**Comment by devgianlu** [comment]
> @devgianlu Is there any reason why we should not use the token we get from login5 and that go-librespot uses to authorize to the web api also for passthrough-requests received by the go-librespot API?

You are right, that should work. The token is even being used for the web API passthrough.

> I implemented an API endpoint for it and during a few short tests it seems to work without any issues so far: [felixstorm@24707f7](https://github.com/felixstorm/go-librespot/commit/24707f74e56f872379e910b031feb8161e4ef71c)
> If you would like me to I will be happy to open a PR for it.

@felixstorm Yes! Feel free to open a PR!

**Comment by txoof** [comment]
I'm eager to test this out if that's helpful.
