### ISSUE TITLE
remove shannon approach

### ISSUE THREAD

**Issue by 3052** [devgianlu/go-librespot#23]
neither the current web client or android client use the shannon code any more:

https://github.com/devgianlu/go-librespot/blob/master/ap/shannon.go

web client uses websocket, and Android uses normal HTTP

**Comment by devgianlu** [comment]
The Shannon code is there purely to support the retrieval of decryption keys for audio streams. Using the new playplay protocol is an open problem because of reverse engineering and aggressiveness of Spotify to cease and desist everything that uses it.

**Comment by devgianlu** [comment]
Oh nice, that would work, but I don't really see the benefit of doing it since the current implementation works file for now. If they ever shut it down or we are forced to move out of it to implement some new fancy features, then we might consider other opportunities, such as Widevine (or playplay).

**Comment by 3052** [comment]
actually, it seems for the web client widevine only works for these:

MP4_256_DUAL
MP4_128_DUAL
MP4_256
MP4_128

while these are protected with something else:

OGG_VORBIS_320
OGG_VORBIS_160
OGG_VORBIS_96
AAC_24

has anyone researched this? I am not even sure if you can change the format with the web client, maybe with a premium account?

**Comment by devgianlu** [comment]
Posting this here for future reference: https://github.com/es3n1n/re-unplayplay

**Comment by 3052** [comment]
to add some context, the above is a de-compilation into C code, and is highly obfuscated:

https://github.com/es3n1n/re-unplayplay/blob/master/src/lib/reversals/decrypt_key.cpp

**Comment by devgianlu** [comment]
By following threads around the topic of playplay it seems very not trivial to have it working without Spotify interfering. It looks to me like there is additional work required to have a proper solution that does not require hardcoding tokens.

Additionally, tackling the original topic: the AP is still required for exchanging OAuth2 credentials for stored credentials to be used with Login5. 

Closing this as the scope is too broad. If the two things mentioned above change in the future it may be worth going down this path.
