### ISSUE TITLE
formats missing

### ISSUE THREAD

**Issue by 3052** [devgianlu/go-librespot#24]
formats 18 19 missing

https://github.com/devgianlu/go-librespot/blob/bd02014096d0410c3a47c36f827fee2356afc549/proto/metadata.proto#L288-L300

**Comment by devgianlu** [comment]
https://github.com/librespot-org/librespot-java/issues/857
https://github.com/devgianlu/go-librespot/commit/1a58df1b9cd5b30a930cdfe529dceb72af7ce6f1
