### ISSUE TITLE
Feature request: edit queue or add consume mode

### ISSUE THREAD

**Issue by volumio** [devgianlu/go-librespot#35]
To make gapeless playback work, we use this strategy:
- track 1 and track 2 are part of the same album
- we start playing track 1
- about 5 seconds before track 1 ends, we add track 2 to queue
- this way the daemon shall play them in gapless mode
- after track 1 has finished playing, we remove it from the queue

To achieve this we would need one of the 2:
- Either a consume mode trigger (once a track is played is removed from queue (best option)
- A way to manage the queue from the API

**Comment by devgianlu** [comment]
You should be able to use just the [`add_to_queue`](https://github.com/devgianlu/go-librespot/blob/ef364dbf339ba3bf0b78034f11e51e1a7f34fcf0/api-spec.yml#L240) endpoint as there's no need to remove previous tracks from the queue. Or am I missing something?

**Comment by volumio** [comment]
@devgianlu leaving the track in the spotify queue may provide conflicts and wrong track playback, especially if repeat is enabled on spotify's side

**Comment by devgianlu** [comment]
@volumio Tracks in the queue are evicted automatically once played so it should not be necessary.

**Comment by volumio** [comment]
@devgianlu if tracks are automatically evicted, then there's no need. thanks for confirming
