### ISSUE TITLE
Fetch audio key from seektables

### ISSUE THREAD

**Issue by KagChi** [devgianlu/go-librespot#37]
You can fetch audio key from seektables then try to decrypt the `pssh_widevine` to get the audio key
the url are  `https://seektables.scdn.co/seektable/fileId.json` file id are hex from audio formats

**Comment by KagChi** [comment]
Seems you can only fetch MP4_128 audio key

**Comment by devgianlu** [comment]
I feel like MP4 is not enough to drop the current approach used for OGG.
