### ISSUE TITLE
Fails to start playing track on RPi4 Alsa error

### ISSUE THREAD

**Issue by peterdk** [devgianlu/go-librespot#39]
Just tried this out on RPi4 Ubuntu 22.04 arm64. Downloaded as binary from Github 0.0.15 release

I can see the 'speaker' in my desktop Spotify, but when playing a track it fails:
```
/opt/go-librespot$ ./go-librespot 
INFO[0000] generated new device id: 8689786ff7807fc2c3b43233fc96462fa98401bb 
WARN[0007] reducing track normalisation factor to prevent clipping, please add negative pregain to avoid 
WARN[0007] failed handling dealer request                error="failed loading current track (transfer): failed creating stream for spotify:track:7gTVQWqEGrqTuZkXpe43z1: ALSA error at snd_pcm_hw_params_set_format: Invalid argument"
```
I use a HifiBerry HAT.

**Comment by peterdk** [comment]
Spocon with Librespot-Java works fine.

**Comment by devgianlu** [comment]
Hvae a look at https://github.com/devgianlu/go-librespot/issues/29#issuecomment-2038153676, I think it might be the same issue.
