### ISSUE TITLE
Seeking results in no sound on some occasions

### ISSUE THREAD

**Issue by volumio** [devgianlu/go-librespot#44]
Seeked a track from Volumio UI, one time it did go well, the other one I got no sound playing. 

UPDATE: The daemon does not respond anymore to command from Volumio after this happens, probably it crashed.

Jun 05 08:34:01 motivo go-librespot[6662]: time="2024-06-05T08:34:01Z" level=debug msg="fetched chunk 4/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:14 motivo go-librespot[6662]: time="2024-06-05T08:34:14Z" level=debug msg="fetched chunk 5/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:28 motivo go-librespot[6662]: time="2024-06-05T08:34:28Z" level=debug msg="fetched chunk 6/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:29 motivo volumio[6434]: info: CoreCommandRouter::volumioSeek
Jun 05 08:34:29 motivo volumio[6434]: info: CoreStateMachine::seek
Jun 05 08:34:29 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:29 motivo volumio[6434]: info: TRACKBLOCK {"uri":"spotify:track:1Yeivlu08disi4wnPDmlGx","service":"spop","name":"On The Run - 2023 Remaster","artist":"Pink Floyd","album":"The Dark Side Of The Moon (50th Anniversary) [2023 Remaster]","type":"song","duration":213,"albumart":"https://i.scdn.co/image/ab67616d0000b2738fe90794e22713f14c4e2622","samplerate":"320 kbps","bitdepth":"16 bit","bitrate":"","codec":"ogg","trackType":"spotify"}
Jun 05 08:34:29 motivo volumio[6434]: info: CoreStateMachine::startPlaybackTimer
Jun 05 08:34:29 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:29 motivo volumio[6434]: info: Spotify seek to: 181000
Jun 05 08:34:29 motivo volumio[6434]: info: Sending Spotify command with payload to local API: /player/seek
Jun 05 08:34:29 motivo volumio[6434]: info: CoreStateMachine::pushState
Jun 05 08:34:29 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:29 motivo volumio[6434]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 05 08:34:29 motivo volumio[6434]: info: CoreCommandRouter::volumioPushState
Jun 05 08:34:29 motivo volumio[6434]: info: MRS: Pushing multiroomSync output update for this device
Jun 05 08:34:29 motivo volumio[6434]: info: MRS: Pushing multiroomSync output
Jun 05 08:34:29 motivo volumio[6434]: info: Signalling Playback active due to playback status change
Jun 05 08:34:29 motivo volumio[6434]: info: Updating  RAAT Signal Path
Jun 05 08:34:29 motivo volumio[6434]: SPOTIFY: RECEIVED VOLUMIO VOLUME 42
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="seek track to 181000ms"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="fetched chunk 13/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=trace msg="seek to 181000ms (diff: 216ms, samples: 7982100, bytes: 7283403)" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="fetched chunk 16/16, size: 62680" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="put connect state because PLAYER_STATE_CHANGED"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="fetched chunk 15/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:29 motivo go-librespot[6662]: time="2024-06-05T08:34:29Z" level=debug msg="fetched chunk 14/16, size: 524288" uri="spotify:track:1Yeivlu08disi4wnPDmlGx"
Jun 05 08:34:48 motivo volumio[6434]: info: CoreCommandRouter::volumioSeek
Jun 05 08:34:48 motivo volumio[6434]: info: CoreStateMachine::seek
Jun 05 08:34:48 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:48 motivo volumio[6434]: info: TRACKBLOCK {"uri":"spotify:track:1Yeivlu08disi4wnPDmlGx","service":"spop","name":"On The Run - 2023 Remaster","artist":"Pink Floyd","album":"The Dark Side Of The Moon (50th Anniversary) [2023 Remaster]","type":"song","duration":213,"albumart":"https://i.scdn.co/image/ab67616d0000b2738fe90794e22713f14c4e2622","samplerate":"320 kbps","bitdepth":"16 bit","bitrate":"","codec":"ogg","trackType":"spotify"}
Jun 05 08:34:48 motivo volumio[6434]: info: CoreStateMachine::startPlaybackTimer
Jun 05 08:34:48 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:48 motivo volumio[6434]: info: Spotify seek to: 141000
Jun 05 08:34:48 motivo volumio[6434]: info: Sending Spotify command with payload to local API: /player/seek
Jun 05 08:34:48 motivo volumio[6434]: info: CoreStateMachine::pushState
Jun 05 08:34:48 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:48 motivo volumio[6434]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 05 08:34:48 motivo volumio[6434]: info: CoreCommandRouter::volumioPushState
Jun 05 08:34:48 motivo volumio[6434]: info: MRS: Pushing multiroomSync output update for this device
Jun 05 08:34:48 motivo volumio[6434]: info: MRS: Pushing multiroomSync output
Jun 05 08:34:48 motivo volumio[6434]: info: Signalling Playback active due to playback status change
Jun 05 08:34:48 motivo volumio[6434]: info: Updating  RAAT Signal Path
Jun 05 08:34:48 motivo volumio[6434]: SPOTIFY: RECEIVED VOLUMIO VOLUME 42
Jun 05 08:34:52 motivo volumio[6434]: info: CoreCommandRouter::volumioSeek
Jun 05 08:34:52 motivo volumio[6434]: info: CoreStateMachine::seek
Jun 05 08:34:52 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:52 motivo volumio[6434]: info: TRACKBLOCK {"uri":"spotify:track:1Yeivlu08disi4wnPDmlGx","service":"spop","name":"On The Run - 2023 Remaster","artist":"Pink Floyd","album":"The Dark Side Of The Moon (50th Anniversary) [2023 Remaster]","type":"song","duration":213,"albumart":"https://i.scdn.co/image/ab67616d0000b2738fe90794e22713f14c4e2622","samplerate":"320 kbps","bitdepth":"16 bit","bitrate":"","codec":"ogg","trackType":"spotify"}
Jun 05 08:34:52 motivo volumio[6434]: info: CoreStateMachine::startPlaybackTimer
Jun 05 08:34:52 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:52 motivo volumio[6434]: info: Spotify seek to: 44000
Jun 05 08:34:52 motivo volumio[6434]: info: Sending Spotify command with payload to local API: /player/seek
Jun 05 08:34:52 motivo volumio[6434]: info: CoreStateMachine::pushState
Jun 05 08:34:52 motivo volumio[6434]: info: CorePlayQueue::getTrack 2
Jun 05 08:34:52 motivo volumio[6434]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 05 08:34:52 motivo volumio[6434]: info: CoreCommandRouter::volumioPushState
Jun 05 08:34:52 motivo volumio[6434]: info: MRS: Pushing multiroomSync output update for this device
Jun 05 08:34:52 motivo volumio[6434]: info: MRS: Pushing multiroomSync output
Jun 05 08:34:52 motivo volumio[6434]: info: Signalling Playback active due to playback status change
Jun 05 08:34:52 motivo volumio[6434]: info: Updating  RAAT Signal Path
Jun 05 08:34:52 motivo volumio[6434]: SPOTIFY: RECEIVED VOLUMIO VOLUME 42

**Comment by devgianlu** [comment]
Quite a lot of stuff has changed in the playback / output driver code, hopefully it has fixed itself.
