### ISSUE TITLE
Playback Reporting

### ISSUE THREAD

**Issue by simpsoon52** [devgianlu/go-librespot#46]
I've been trying to figure out if the latest Spotify client (desktop) is fully migrated to HTTP(s) and while a lot of the requests are, I still can't seem to sniff out some playback reporting requests which makes me think it's still being done over Mercury requests.

For example, once a track finishes playing at a certain point, librespot-java used to send the stream reporting data back to Spotify over Hermes as here: https://github.com/librespot-org/librespot-java/blob/dev/player/src/main/java/xyz/gianlu/librespot/player/metrics/TrackTransitionEvent.java

Do I need to reimplement Mercury requests to be able to do this?

Is there any way I can sniff the Mercury requests since the old spotify analyze tools seem to be outdated so any guidance on how I can do it myself would be appreciated. I'll work on making a PR once I have some guidance and can push it with the new updated Go library

**Comment by IterioDev** [comment]
stop trying to get spoonfed on how to make spotify bots, you are so obvious in every one of your issues amongst many other users. Do some research yourself
