### ISSUE TITLE
Interacting breaks connection

### ISSUE THREAD

**Issue by fireFerry** [devgianlu/go-librespot#48]
Hello,

First of all I would like to start off by thanking you for making this project and putting the time and effort into maintaining it!

Whenever I connect to my device and start playing music, things work. Up until a few songs have played, or I interact with the player too much by skipping the song or seeking in the song. It will disconnect my phone from the player and it will disappear from the spotify connect list. Even in the trace log_level mode, I'm getting no errors beside `ERRO[0121] did not receive last pong from dealer, 60s passed` every few seconds. I can send you the full trace if interested.

EDIT: Also found a typo haha: 
![afbeelding](https://github.com/user-attachments/assets/d0290535-3ae3-42ef-a3f2-64dcfdf3ae2c)

**Comment by devgianlu** [comment]
Thank you for reporting, this has probably something to do with a deadlock somewhere that makes the player unresponsive.

**Comment by devgianlu** [comment]
Closing this as there has been lots of improvements in the stability of the connection (still lots to do).
