### ISSUE TITLE
Cross-compiling on ubuntu x86_64 to darwin amd64 fails with error in output.go and clang

### ISSUE THREAD

**Issue by andrewl** [devgianlu/go-librespot#52]
`GOOS=darwin GOARCH=amd64=1 go build -o go-librespot-daemon ./cmd/daemon

go-librespot/output
output/output.go:8:3: undefined: output
output/output.go:56:14: undefined: newOutput

runtime/cgo
clang: error: argument unused during compilation: '-arch x86_64' [-Werror,-Wunused-command-line-argument]
`

**Comment by devgianlu** [comment]
There is no output driver available for Darwin. Only ALSA is currently supported.

**Comment by andrewl** [comment]
Ah, that's a shame - was hoping to get spotify output on an old 2009 macbook. Thanks for the quick response.

**Comment by devgianlu** [comment]
The output driver for Windows is also not supported, but that one at least I can test. The MacOS one seems a bit of a nightmare. If you wanted to try and implement it yourself you can get insipiration from [oto](https://github.com/ebitengine/oto).

**Comment by tooxo** [comment]
> Ah, that's a shame - was hoping to get spotify output on an old 2009 macbook. Thanks for the quick response.

If you are still interested, I just put up a PR implementing macos audio, it would be very helpful if you could test it on your device, and maybe provide some kind of feedback! @andrewl #59
