### ISSUE TITLE
Failed authenticating accesspoint

### ISSUE THREAD

**Issue by samhza** [devgianlu/go-librespot#53]
```
failed authenticating accesspoint with username and password: failed authenticating: failed login: BadCredentials
```

Spotify seems to have made a change that breaks authentication. Related issue: librespot-org/librespot#1308

**Comment by devgianlu** [comment]
You should be able to use interactive login: https://github.com/devgianlu/go-librespot/commit/1e82a276812d5ef5ca0a52fe7d993ea549667a17
