### ISSUE TITLE
feat: go gettable module path

### ISSUE THREAD

**Issue by marcus-crane** [devgianlu/go-librespot#56]
Hey there,

First of all, amazing work on go-librespot and reverse engineering all of the Spotify stuff (dealer gateway etc).

I was actually looking to use parts of `go-librespot` as a library just to request my player state and use it to power a playback widget.

I realise that `go-librespot` isn't intended to be used as a library of course but it's all wired up nicely enough that it does actually work and I have a minimum implementation using both the `dealer` and `spclient` packages to receive messages.

The only remaining thing is that `go-librespot` is not actually importable as a standard Go library, due to its module path in `go.mod` not being a valid path.

Basically, `go get` expects the path that you require a package from (in this case, the Github URL) to be the same as the module path ([the `module` directive in go.mod](https://github.com/devgianlu/go-librespot/blob/master/go.mod#L1))

![CleanShot 2024-08-03 at 13 18 46@2x](https://github.com/user-attachments/assets/7c00fa4c-d8e4-43e5-96b7-ffc2f976615f)

I realise of course that supporting usage as a library is an entirely different thing than supporting an audio client so I don't expect that anyone using it as a library should expect any guarantees around breaking changes, interfaces staying public and so on.

It just turns out that everything in Go is importable as a library whether intended or not so it's a nice side effect to support even if it's not explicitly offered.

In the meantime, I've been getting by with cloning `go-librespot` into my local repo and then adding the following to my `go.mod` file as a workaround:

```go
replace go-librespot => ./go-librespot

require (
	go-librespot v0.0.0-00010101000000-000000000000
)
```

Much appreciated 🙂

**Comment by devgianlu** [comment]
You are most definitely right, the module name should match that of the repository. I have updated it: https://github.com/devgianlu/go-librespot/commit/34f6371d9d1271ad74dcc8afd3fbff78480afd9a

**Comment by marcus-crane** [comment]
Thanks! I can remove my temporary git cloned repo but glad to say that I got a nice working Spotify Connect client with your great library 🙂
