### ISSUE TITLE
Player drops too early

### ISSUE THREAD

**Issue by tooxo** [devgianlu/go-librespot#60]
In https://github.com/devgianlu/go-librespot/blob/master/player/player.go#L142 , the output is instructed to drop all queued frames, resulting in the end of the song missing, when one song goes over to the next without skipping.

My proposed solution: Only drop the frames, when the set command resulted from a skip and not a song regularly ending.
Alternative solution, if the above is not possible: Only drop the frames, when there is no secondary source configured. This would result in delayed skipping, if the song is in its last 30 seconds or so.

**Comment by devgianlu** [comment]
Opted for the first solution.
