### ISSUE TITLE
Redundant warning?

### ISSUE THREAD

**Issue by phts** [devgianlu/go-librespot#7]
https://github.com/devgianlu/go-librespot/blob/6eabc83834d25325e9ef2c0a1ff1b0e546e64c40/cmd/daemon/controls.go#L198

**Comment by devgianlu** [comment]
The warning will be removed when shuffling context is supported. It is there so that people can understand why it's not working by looking at the logs.

**Comment by phts** [comment]
What exactly does not work yet? As I tried how it works, seemed it worked and shuffle was toggled

**Comment by devgianlu** [comment]
There's no logic to handle the shuffling, it just shows whether shuffling is enabled.
