### ISSUE TITLE
long playlists are not fetched completely when started from certain devices

### ISSUE THREAD

**Issue by tooxo** [devgianlu/go-librespot#70]
I just noticed, that if I run go-librespot and try to start a playlist on there from a up-to-date mac desktop version of the spotify client it just fetches 25 songs, even if there are more tracks in the playlist. When I debugged this, I realized the nextPageUrl of the Page in the response is empty. Is there maybe a workaround for this which could be implemented?

From what it seems like, the paging seems not to be used in the android implementation anyway, here it just sends one page with all the tracks included.

**Comment by devgianlu** [comment]
Closing :wink:
