### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by Willyarma** [devgianlu/go-librespot#80]
I had written a node.js wrapper for librespot-java, it was capable of spawning multiple instances of librespot-java.
I was using the command line options --deviceName and --player.mixerSearchKeywords so that I could map each instance to a different audio devcie and name it of course.
I didnt have any trouble with having a single config file for all instances.

Would it possible to add this to the go version? Would it work?

**Comment by Willyarma** [comment]
I'm just testing out this version now.
I noticed that it dosent report available mixers, can this be added too?

**Comment by devgianlu** [comment]
@Willyarma If you are willing to have multiple configuration files you can use `-config_path` and `-credentials_path` to specify the position of those two.

**Comment by Willyarma** [comment]
Thanks, I'll try it out!
Overriding parameters from the command line would be nicer and avoid messy multiple config files but this ought to work for what I want to do.

Is this new or did I completely miss it?

**Comment by Willyarma** [comment]
I've been struggling to get it working, not sure where the problem lies, whether its node.js, go or me.
When I use the child_process.spawn function from node.js, go-librepot completley ignores the command line arguments unless I set the shell flag option to true so that it runs inside a shell instead of directly.
This worked fine on the java version.

**Comment by devgianlu** [comment]
> When I use the child_process.spawn function from node.js, go-librepot completley ignores the command line arguments unless I set the shell flag option to true so that it runs inside a shell instead of directly.

@Willyarma You may need to pass each parameter as different element of the command array:

```js
spawn('go-librespot', ['-config_path', '/path/to/config.yml', '-credentials_path', '/path/to/creds.json']);
```
